### ISSUE TITLE
Should categories be used?

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/fredrikaverpil.github.io#7]
Example in **post entry**:

```yaml
---
layout: post
title: How To Use Tags And Categories On GitHub Pages Without Plugins
category: programming
tags: [github, github-pages, jekyll]
---
```

For a more complex implementation and categories:: https://github.com/minddust/minddust.github.io
